name: CI

on:
  push:
    branches: [main]
    tags: ["v[0-9]+.*"]
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Rust ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/verify
      - run: cargo doc --locked --no-deps
      - run: cargo build --locked --release
      - if: runner.os == 'Linux'
        run: cargo package --locked
